import './globals.scss';
import { TimeProvider } from '@creo/common';

export const metadata = {
  title: 'Welcome to creo-web-auth',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TimeProvider>
        <body className="bg-black">{children}</body>
      </TimeProvider>
    </html>
  );
}
